name: ChestShop
main: ChestShop\Main
api: [2.0.0, 3.0.0, 3.0.0-ALPHA4]
version: 2.0
depend: [EconomyAPI]
commands:
  chestshop:
    aliases: ["cs", "cshop"]
permissions:
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
