name: ChestShop
main: ChestShop\Main
api: [2.0.0, 3.0.0, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 3.0
depend: [EconomyAPI]
commands:
  chestshop:
    aliases: ["cs", "cshop"]
permissions:
  chestshop.command.opcmd:
    default: op
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
